from websocket import create_connection

ws = create_connection("ws://127.0.0.1:9001/runCase?casetuple=1.1.2&agent=my_websocket_client")
print("Sending 'Hello, World'...")
ws.send("Hello, World")
print("Sent")
print("Receiving...")
result =  ws.recv()
ws.send("Hello, World")
print("Received '%s'" % result)
ws.send("Hello, World")
result =  ws.recv()
ws.send("Hello, World")
print("Received '%s'" % result)
ws.send("Hello, World")
result =  ws.recv()
ws.send("Hello, World")
print("Received '%s'" % result)
ws.send("Hello, World")
result =  ws.recv()
ws.send("Hello, World")
print("Received '%s'" % result)
ws.close()
